export const Subjects = [
  {
    name: "Construction Studies",
    group: "Practical",
    usage: "Secondary",
    Topics: [],
  },
  { name: "Engineering", group: "Practical", usage: "Secondary", Topics: [] },
  { name: "Technology", group: "Practical", usage: "Secondary", Topics: [] },
  { name: "Applied Maths", group: "Science", usage: "Secondary", Topics: [] },
  {
    name: "Agricultural Science",
    group: "Science",
    usage: "Primary",
    Topics: [
      { name: "Animal Diseases" },
      { name: "Animal Physiology" },
      { name: "Animal Production (All animals)" },
      { name: "Beef and Dairy Cattle" },
      { name: "Classification of Organisms" },
      { name: "Crop Production" },
      { name: "Describe an Experiment..." },
      { name: "Fertilisers, Pollution & the Environment" },
      { name: "Genetics" },
      { name: "Give a scientific explanation for..." },
      { name: "Grassland" },
      { name: "IDENTIFICATIONS - Animals" },
      { name: "IDENTIFICATIONS - Plants" },
      { name: "Pigs" },
      { name: "Sheep" },
      { name: "Soil Science" },
    ],
  },
  {
    name: "Biology",
    group: "Science",
    usage: "Primary",
    Topics: [
      { name: "Bacteria, Viruses, Fungi + Yeast" },
      { name: "Blood & Circulatory System" },
      { name: "Breathing System" },
      { name: "Cell Division" },
      { name: "Cell Metabolism & Enzymes" },
      { name: "Cell Structure" },
      { name: "Digestive System" },
      { name: "Ecology & Ecosystems" },
      { name: "Excretion" },
      { name: "Experiment Questions" },
      { name: "Eye/Ear & Nervous system" },
      { name: "Food & Food tests" },
      { name: "Genetics, DNA & Evolution" },
      { name: "Hormonal/Endrocrine System" },
      { name: "Human Reproduction" },
      { name: "Immune system" },
      { name: "Musculoskeletal System" },
      { name: "Photosynthesis" },
      { name: "Plant Reproduction" },
      { name: "Plant Responses & Seed growth" },
      { name: "Plant Responses & Seed growth" },
      { name: "Plant Structure" },
      { name: "Plant Transport and Osmosis" },
      { name: "Respiration" },
      { name: "The Scientific Method" },
    ],
  },
  {
    name: "Chemistry",
    group: "Science",
    usage: "Primary",
    Topics: [
      { name: "Acids, Bases & PH calculations" },
      { name: "Atomic Structure" },
      { name: "Chemical Equilibrium" },
      { name: "Electron Arrangement" },
      { name: "Experiment Q1 (Titration)" },
      { name: "Experiment Q2 (Organic)" },
      { name: "Experiment Q3 (Other)" },
      { name: "Fuels & Thermochemistry" },
      { name: "Gas Laws, moles & Gas Properties" },
      { name: "Instrumentation & Chromatography" },
      { name: "Ionic & Covalent Bonding" },
      { name: "Option: Atmospheric Chemistry" },
      { name: "Option: Industrial Chemistry" },
      { name: "Option: Materials & Polymers" },
      { name: "Option: Metals" },
      { name: "Organic Chemistry" },
      { name: "Oxidation & Reduction" },
      { name: "Periodic Table" },
      { name: "Radioactivity" },
      { name: "Rates of Reaction" },
      { name: "Stoichiometry, Formulae & Equations" },
      { name: "Water & Water Analysis" },
    ],
  },
  {
    name: "Mathematics",
    group: "Science",
    usage: "Primary",
    Topics: [
      { name: "Algebra" },
      { name: "Area & Volume" },
      { name: "Complex Numbers" },
      { name: "Co-Ordinate Geometry, The Line" },
      { name: "Differentiation" },
      { name: "Financial Maths/Arithmetic" },
      { name: "Functions" },
      { name: "Geometry" },
      { name: "Geometry (Proofs and Constructions)" },
      { name: "Graphs of Functions" },
      { name: "Induction" },
      { name: "Integration" },
      { name: "Logs" },
      { name: "Probability" },
      { name: "Roots of a Function/ Equation" },
      { name: "Sequences & Series" },
      { name: "Sets" },
      { name: "Statistics & Data" },
      { name: "The Circle" },
      { name: "Trigonometry" },
    ],
  },
  {
    name: "Physics",
    group: "Science",
    usage: "Primary",
    Topics: [
      { name: "Acceleration" },
      { name: "Applied Electricity" },
      { name: "Circular Motion" },
      { name: "Current & Charge" },
      { name: "Electric Circuits" },
      { name: "Electromagnetic Induction" },
      { name: "Exp. Qs (all)" },
      { name: "Exp. Qs. -  Electricity" },
      { name: "Exp. Qs. -  Heat" },
      { name: "Exp. Qs. -  Light" },
      { name: "Exp. Qs. -  Mechanics" },
      { name: "Exp. Qs. -  Sound" },
      { name: "Force,Mass & Momentum" },
      { name: "Heat & Heat Transfer" },
      { name: "Light" },
      { name: "Magnets and Magnetic Fields" },
      { name: "Nuclear Energy" },
      { name: "Particle Physics" },
      { name: "Potential Difference & Capacitance" },
      { name: "Pressure, Gravity & Moments" },
      { name: "Reflection & Mirrors" },
      { name: "Refraction & Lenses" },
      { name: "Resistance" },
      { name: "Semiconductors" },
      { name: "Simple Harmonic Motion" },
      { name: "Speed, Displacement, Velocity" },
      { name: "Static Electricity" },
      { name: "Temperature & Thermometers" },
      { name: "The Atom, Nucleus & Radioactivity" },
      { name: "The Electron" },
      { name: "Vectors & Scalars" },
      { name: "Vibration & Sound" },
      { name: "Waves & Wave Motion" },
      { name: "Work, Energy & Power" },
    ],
  },
  {
    name: "Physics and Chemistry",
    group: "Science",
    usage: "Secondary",
    Topics: [],
  },
  {
    name: "Computer Science",
    group: "Science",
    usage: "Secondary",
    Topics: [],
  },
  { name: "Art", group: "Artistic", usage: "Secondary", Topics: [] },
  { name: "Music", group: "Artistic", usage: "Secondary", Topics: [] },
  {
    name: "Design & Comm Graphics",
    group: "Artistic",
    usage: "Secondary",
    Topics: [],
  },
  { name: "Arabic", group: "Humanities", usage: "Secondary", Topics: [] },
  {
    name: "Classical Studies",
    group: "Humanities",
    usage: "Secondary",
    Topics: [],
  },
  {
    name: "English",
    group: "Humanities",
    usage: "Primary",
    Topics: [
      { name: "1 Composition (Personal Writing)" },
      { name: "1 Reading Comprehension" },
      { name: "Comparative - Cultural Context " },
      { name: "Comparative - Literary genre (2020)" },
      { name: "Comparative - Theme or Issue" },
      { name: "Comparative - Vision & Viewpoint (2021)" },
      { name: "Hamlet (2020)" },
      { name: "King Lear" },
      { name: "Othello" },
      { name: "Poetry - Bishop (2021)" },
      { name: "Poetry - Boland (2020/21)" },
      { name: "Poetry - Dickinson (2020)" },
      { name: "Poetry - Durcan (2020/21)" },
      { name: "Poetry - Frost (2020/21)" },
      { name: "Poetry - Heaney (2021)" },
      { name: "Poetry - Hopkins (2021)" },
      { name: "Poetry - Keats (2021)" },
      { name: "Poetry - Lawrence (2020)" },
      { name: "Poetry - Ni Chuilleanain (2020)" },
      { name: "Poetry - Plath (2021)" },
      { name: "Poetry - Rich (2020)" },
      { name: "Poetry - Wordsworth (2020)" },
      {
        name:
          "Text - (2021) Persepolis: The Story of a Childhood and the Story of a Return",
      },
      { name: "Text - All My Sons" },
      { name: "Text - Americanah" },
      { name: "Text - Never Let me Go (2021)" },
      { name: "Text - Persuasion " },
      { name: "Text - The Great Gatsby " },
      { name: "Text - The Handmaid's Tale" },
      { name: "Text - Wuthering Heights " },
      { name: "The Tempest" },
      { name: "Unseen Poetry" },
    ],
  },
  {
    name: "French",
    group: "Humanities",
    usage: "Primary",
    Topics: [
      { name: "AURAL - Conversation" },
      { name: "AURAL - Interview " },
      { name: "AURAL - News Pieces" },
      { name: "Literary/Novel Comprehension" },
      { name: "Newspaper/Magazine Comprehension" },
      { name: "Opinion - Animals, nature and the environment" },
      { name: "Opinion - Education" },
      { name: "Opinion - Health" },
      { name: "Opinion - Ireland, travel, tourism and culture" },
      { name: "Opinion - Politics, social issues and equality" },
      { name: "Opinion - Sport" },
      { name: "Opinion - Technology and media" },
      { name: "Opinion - Youth, teenagers and families" },
      { name: "ORAL exam" },
      { name: "Write a Diary..." },
      { name: "Write a letter..." },
      { name: "Write a Note..." },
      { name: "Write an eMail..." },
      { name: "Written Production (recit)" },
    ],
  },
  {
    name: "Irish",
    group: "Humanities",
    usage: "Primary",
    Topics: [
      { name: "AURAL - ComhrÃ¡ (Conversation)" },
      { name: "AURAL - PhÃ­osa Nuachta (News Pieces)" },
      { name: "AURALS - FÃ³gra (Announcement)" },
      { name: "ORAL exam" },
      { name: "Poetry - An SpailpÃ­n FÃ¡nach" },
      { name: "Poetry - An tEarrach Thiar" },
      { name: "Poetry - Colscaradh" },
      { name: "Poetry - GÃ©ibheann" },
      { name: "Poetry - Mo GhrÃ¡-sa" },
      { name: "Poetry, extra - A Chlann" },
      { name: "Poetry, extra - Caoineadh AUL" },
      { name: "Poetry, extra - ColmÃ¡in " },
      { name: "Poetry, extra - Eiceolai" },
      { name: "Poetry, extra - Fill Aris" },
      { name: "Prose - A thig NÃ¡ Tit Orm" },
      { name: "Prose - An GnÃ¡thrud" },
      { name: "Prose - An Lasair Choille" },
      { name: "Prose - An Triail" },
      { name: "Prose - CÃ¡ca Milis" },
      { name: "Prose - Canary Wharf" },
      { name: "Prose - DÃ­s" },
      { name: "Prose - Gafa" },
      { name: "Prose - Hurlamaboc" },
      { name: "Prose - OisÃ­n I dtÃ­r na nÃ“g" },
      { name: "Prose - TÃ³raÃ­ocht Dhiarmada agus GhrÃ¡inne" },
      { name: "Reading Comprehension" },
      { name: "Studied Poetry (Filiocht Roghnach)" },
      { name: "Studied Prose (Pros Roghnach)" },
      { name: "Write a Debate.." },
      { name: "Write a News/Magazine Article.." },
      { name: "Write a Story.." },
      { name: "Write an Essay.." },
    ],
  },
  {
    name: "Hebrew Studies",
    group: "Humanities",
    usage: "Secondary",
    Topics: [],
  },
  {
    name: "German",
    group: "Humanities",
    usage: "Primary",
    Topics: [
      { name: "AURAL - 1) Interview " },
      { name: "AURAL - 2) Phone Call" },
      { name: "AURAL - 3) Dialogue" },
      { name: "AURAL - 4) News Pieces" },
      { name: "Ã„uÃŸerung zum Thema (Write on a theme)" },
      { name: "Comprehension: Magazine or Newspaper" },
      { name: "Comprehension: Novel or Short story" },
      { name: "Grammatik (Grammar)" },
      { name: "ORAL exam" },
      { name: "Schriftliche Produktion (Picture)" },
      { name: "Schriftliche Produktion (Write a Letter)" },
    ],
  },
  {
    name: "History",
    group: "Humanities",
    usage: "Secondary",
    Topics: [
      { name: "1.IRL Ireland & the Union" },
      { name: "2.IRL Movements for political/social reform" },
      { name: "3.IRL Sovereignty & the impact of partition" },
      { name: "4.IRL The Irish diaspora" },
      { name: "5.IRL Politics & Society in Northern Ireland" },
      { name: "6.IRL Republic - government, society, economy" },
      { name: "EUR1. Nationalism & state formation" },
      { name: "EUR2. Nation states & international tensions" },
      { name: "EUR3. Dictatorship & Democracy" },
      { name: "EUR4. Division & Realignment" },
      { name: "EUR5. Retreat from Empire & aftermath" },
      { name: "EUR6. The United States & the World" },
      { name: "Leaving Cert History Later Modern " },
    ],
  },
  {
    name: "Italian",
    group: "Humanities",
    usage: "Secondary",
    Topics: [
      { name: "AURAL - Conversations" },
      { name: "Aural - News items/statements" },
      { name: "Essay Writing (A ciascuno)" },
      { name: "Essay Writing (Bianca)" },
      { name: "Oral" },
      { name: "Reading Comprehension (A ciascuno...)" },
      { name: "Reading Comprehension (Bianca...) " },
      { name: "Reading Comprehension (Journalistic)" },
      { name: "Reading Comprehension (Literary - Unseen)" },
      { name: "Written Composition - Formal" },
      { name: "Written Composition - Guided" },
      { name: "Written Composition - Opinion Piece" },
    ],
  },
  { name: "Japanese", group: "Humanities", usage: "Secondary", Topics: [] },
  { name: "Latin", group: "Humanities", usage: "Secondary", Topics: [] },
  { name: "Russian", group: "Humanities", usage: "Secondary", Topics: [] },
  {
    name: "Spanish",
    group: "Humanities",
    usage: "Secondary",
    Topics: [
      { name: "Aural - Anuncio/ Announcement" },
      { name: "Aural - Descriptivo/ Description" },
      { name: "Aural - Dialogo/ Dialogue" },
      { name: "Aural - El Tiempo/ Weather" },
      { name: "Aural - Una Noticia/News" },
      { name: "Journalistic Text" },
      { name: "Opinion Text" },
      { name: "ORAL exam" },
      { name: "Prescribed Literature (Sin Noticias de Gurb)" },
      { name: "Short Comprehensions" },
      { name: "Write a Dialogue..." },
      { name: "Write a Letter/email..." },
      { name: "Writer a Diary entry/note..." },
      { name: "Leaving Cert Spanish Discussions" },
    ],
  },
  {
    name: "Other Language",
    group: "Humanities",
    usage: "Secondary",
    Topics: [],
  },
  {
    name: "Ancient Greek",
    group: "Humanities",
    usage: "Secondary",
    Topics: [],
  },
];
