# Generated by Django 3.1.1 on 2020-09-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('question_num', models.CharField(max_length=10)),
                ('question', models.ImageField(upload_to='images/questions')),
                ('marking_scheme', models.ImageField(upload_to='images/marking')),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
    ]
