# Generated by Django 3.1.1 on 2020-09-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='outOf',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
