# Generated by Django 3.1.1 on 2020-09-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_question_outof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marking_scheme',
            field=models.ImageField(null=True, upload_to='images/marking'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.ImageField(null=True, upload_to='images/questions'),
        ),
    ]
